# Generated by Django 2.0.5 on 2018-05-03 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0001_initial'),
        ('task', '0002_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='round',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='round.Round'),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.TextField(default='Defaul title', max_length=255),
            preserve_default=False,
        ),
    ]
