# Generated by Django 2.0.5 on 2018-05-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20180503_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
