# Generated by Django 2.0.5 on 2018-05-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0004_auto_20180506_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa cum odit assumenda ducimus quas unde quaerat, veritatis officiis aliquam in delectus numquam, qui corporis sed quis ullam suscipit vel quasi explicabo praesentium repellat commodi, laboriosam voluptatibus optio. Excepturi est necessitatibus consequuntur deserunt id iste blanditiis quia, quas, minus, officia, qui dolores voluptatibus modi eius molestiae accusamus tempora! Voluptatem rem placeat dolores inventore natus voluptatum nobis illo labore nesciunt dolorem ea tenetur dicta dolorum quas molestias, beatae veritatis nemo laudantium adipisci, iusto praesentium. Accusamus neque perferendis aperiam, vitae eius cumque temporibus et, nam qui, aliquid incidunt autem. Laudantium pariatur sit minus.'),
            preserve_default=False,
        ),
    ]
